# import userbot by apis

from time import sleep
from userbot import CMD_HELP
from userbot.events import register


@register(outgoing=True, pattern="^.wibu2(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(0.07)
    await typew.edit("**Sial Ada Wibu😨**")
    sleep(0.07)
    await typew.edit("**Sekuat Apapun Aku😭**")
    sleep(0.07)
    await typew.edit("**Jika Ada Wibu😨**")
    sleep(0.07)
    await typew.edit("**Aku Harus Lari🏃🏻**")
    sleep(0.07)
    await typew.edit("**Lari Cukkk Ada Wibuuu🏃🏻**")
    sleep(0.07)
    await typew.edit("**Argghh Bangkeee!🏃🏻**")
    sleep(0.07)
    await typew.edit("**Lari Sekencang-Kencangnya🤸🏻**")
    sleep(0.07)
    await typew.edit("**Karena Kita Sedang🤾🏻**")
    sleep(0.07)
    await typew.edit("**Menghadapi Ras Terkuat🤸🏻**")
    sleep(0.07)
    await typew.edit("**Yang Ada Di Dunia🏃🏻**")
    sleep(0.07)
    await typew.edit("**Wibuuuu🪂**")
    sleep(0.07)
    await typew.edit("**Arghhhhhhh🧗🏻**")
    sleep(0.07)
    await typew.edit("**Istrinya Kartun🤾🏻**")
    sleep(0.07)
    await typew.edit("**Dasar Wibu😨**")
    sleep(0.07)
    await typew.edit("**Maaf Wibu🤼‍♂️**")
    sleep(0.07)
    await typew.edit("**Aku Tidak Akan🤾🏻**")
    sleep(0.07)
    await typew.edit("**Mengulanginya Lagi🏃🏻**")
    sleep(0.07)
    await typew.edit("**Tapi Bo'ong🤾🏻**")
    sleep(0.07)
    await typew.edit("**Dasar Wibu, Istri Kartun🪂**")
    sleep(1)
    await typew.edit("**IUHH DEMEN KOK SAMA 2D😖**")


@register(outgoing=True, pattern="^.wibu(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**WI WIII WIIII WIIII.....**")
    sleep(1)
    await typew.edit("__ARGHHH LARI ADA WIBUU!....__")
    sleep(1)
    await typew.edit("`🏃                        🏂`")
    await typew.edit("`🏃                       🏂`")
    await typew.edit("`🏃                      🏂`")
    await typew.edit("`🏃                     🏂`")
    await typew.edit("`🏃   `LARII ADA WIBU`          🏂`")
    await typew.edit("`🏃                   🏂`")
    await typew.edit("`🏃                  🏂`")
    await typew.edit("`🏃                 🏂`")
    await typew.edit("`🏃                🏂`")
    await typew.edit("`🏃               🏂`")
    await typew.edit("`🏃              🏂`")
    await typew.edit("`🏃             🏂`")
    await typew.edit("`🏃            🏂`")
    await typew.edit("`🏃           🏂`")
    await typew.edit("`🏃..Tolong..🏂`")
    await typew.edit("`🏃           🏂`")
    await typew.edit("`🏃            🏂`")
    await typew.edit("`🏃             🏂`")
    await typew.edit("`🏃              🏂`")
    await typew.edit("`🏃               🏂`")
    await typew.edit("`🏃                🏂`")
    await typew.edit("`🏃                 🏂`")
    await typew.edit("`🏃                  🏂`")
    await typew.edit("`🏃                   🏂`")
    await typew.edit("`🏃                    🏂`")
    await typew.edit("`🏃                     🏂`")
    await typew.edit("`🏃  Huh-Huh-Huh       🏂`")
    await typew.edit("`🏃                   🏂`")
    await typew.edit("`🏃                  🏂`")
    await typew.edit("`🏃                 🏂`")
    await typew.edit("`🏃                🏂`")
    await typew.edit("`🏃               🏂`")
    await typew.edit("`🏃              🏂`")
    await typew.edit("`🏃             🏂`")
    await typew.edit("`🏃            🏂`")
    await typew.edit("`🏃           🏂`")
    await typew.edit("`🏃          🏂`")
    await typew.edit("`🏃         🏂`")
    await typew.edit("__KOK MAKIN DEKET SI WIBU__")
    sleep(1)
    await typew.edit("`🏃       🏂`")
    await typew.edit("`🏃      🏂`")
    await typew.edit("`🏃     🏂`")
    await typew.edit("`🏃    🏂`")
    await typew.edit("**Untung Ngga Kena Njir**")
    sleep(1)
    await typew.edit("🎯")
    sleep(2)
    await typew.edit("**Mampus Kau Wibu**")


CMD_HELP.update({
    "wibu": "𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.wibu`\
    \n↳ : untuk melihat sesuatu yng menarik\
    \n\n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.wibu2`\
    \n↳ : Lari cukk ada wibuu aarrghh."
})
